from abc import ABC, abstractmethod
from typing import Dict, Optional, Any, List
from dataclasses import dataclass

@dataclass
class LLMResponse:
    content: Any
    usage_metadata: Optional[Dict[str, int]] = None


class LLMInterface(ABC):
    @property
    @abstractmethod
    def model_id(self) -> str:
        """Returns the identifier of the underlying model."""
        pass

    @property
    @abstractmethod
    def embedding_dimension(self) -> int:
        """Returns the dimension of the embeddings generated by this model."""
        pass

    @abstractmethod
    async def generate(self, prompt: str, config: Optional[Dict[str, Any]] = None) -> LLMResponse:
        """
        Generates text.
        Returns LLMResponse(content=str, usage_metadata=dict).
        """
        pass
    
    @abstractmethod
    async def embed_documents(self, texts: List[str]) -> List[List[float]]:
        """
        Embeds a list of texts for storage (Database).
        """
        pass
    
    @abstractmethod
    async def embed_query(self, text: str) -> List[float]:
        """
        Embeds a single query for searching (Retrieval).
        """
        pass

    @abstractmethod
    async def upload_file(self, file_path: str, mime_type: str):
        """
        Upload a file to the LLM provider's File API.
        Returns a file reference for use in subsequent calls.
        """
        pass

    @abstractmethod
    async def extract_structured_resume(self, file_ref) -> LLMResponse:
        """
        Fallback: Extract and structure a resume from an uploaded file.
        Returns LLMResponse(content=dict, usage_metadata=dict).
        """
        pass

    @abstractmethod
    async def structure_resume_batch(self, markdown_texts: List[str]) -> LLMResponse:
        """
        Structure 2-3 locally-parsed markdown CVs into parsed_data JSON.
        Returns LLMResponse(content=list[dict], usage_metadata=dict).
        """
        pass
